---@alias numberInput NumberInputField -- UI NumberInput
---@
---@class AddCheckbox
---@field isBox boolean  -- When true, the element is a box.
---@
---@class AddNumberInput
---@field isBox boolean  -- When false, the element is not a box.
---@field max number     -- Maximum value, only if isBox is false.
---@field initial number -- Initial value, only if isBox is false.
---@
---@alias SettingsTable table<ModSettingsNames, {isBox:boolean, max?:number,initial?:number , text:string}>  -- Config for all Mod settings
---@
---@alias addUiInput AddCheckbox | AddNumberInput
---@
---@alias ModSettingsNames
---| '"cityWalls"' # The size of city Walls
---| '"naturalCityGrowth"' # Boolean if the city can grow
---| '"maxCitySize"' # Boolean for enforcing max city size
---| '"bombCardDamagesCities"' # Boolean if bomb card damages a city
---| '"wastelandNeutralCities"' # Boolean for neutral territories having cities
---| '"extraArmiesInCity"' # Boolean for getting extra armies when deploying in a city
---| '"deployOrdersOutsideCitySkipped"' # Boolean for only allowing deploys on a city
---| '"unfogCities"' # Boolean for making cities visible to everyone
---
